import React from 'react';
import { createRoot } from 'react-dom/client';
import {
  Breadcrumbs,
  Button,
  Checkbox,
  CheckboxGroup,
  Disclosure,
  DisclosureGroup,
  Autocomplete,
  DateField,
  DatePicker,
  DateRangePicker,
  Form,
  Group,
  Link,
  Meter,
  NumberField,
  ProgressBar,
  SearchField,
  Separator,
  Switch,
  TextField,
  TimeField,
  ToggleButton,
  Calendar,
  ColorArea,
  ColorField,
  ColorPicker,
  ColorSlider,
  ColorSwatch,
  ColorSwatchPicker,
  ColorWheel,
  ComboBox,
  GridList,
  ListBox,
  Menu,
  RadioGroup,
  RangeCalendar,
  Select,
  Slider,
  Table,
  Tabs,
  TagGroup,
  ToggleButtonGroup,
  TokenField,
  Toolbar,
  Tree,
  Virtualizer,
} from '@core-ui/react';
import { R1ButtonFixture } from '../../../packages/react/src/button-fixture.mjs';
import '@core-ui/react/styles.css';

const profiles = [
  ['light', 'standard', 'full', 'comfortable', 'ltr'],
  ['dark', 'standard', 'full', 'comfortable', 'ltr'],
  ['light', 'more', 'full', 'comfortable', 'ltr'],
  ['light', 'standard', 'reduced', 'comfortable', 'ltr'],
  ['light', 'standard', 'full', 'compact', 'ltr'],
  ['light', 'standard', 'full', 'comfortable', 'rtl'],
];

function ComponentStates() {
  return React.createElement(React.Fragment, null,
    React.createElement('article', { 'data-component': 'breadcrumbs' },
      React.createElement('h3', null, 'Breadcrumbs'),
      React.createElement(Breadcrumbs, { 'aria-label': 'Breadcrumb', items: [{ id: 'home', label: 'Home', href: '/' }, { id: 'docs', label: 'Docs' }] })),
    React.createElement('article', { 'data-component': 'checkbox' },
      React.createElement('h3', null, 'Checkbox'),
      React.createElement(Checkbox, { defaultChecked: true }, 'Selected'),
      React.createElement(Checkbox, { indeterminate: true }, 'Mixed'),
      React.createElement(Checkbox, { disabled: true }, 'Disabled')),
    React.createElement('article', { 'data-component': 'autocomplete' },
      React.createElement('h3', null, 'Autocomplete'),
      React.createElement(Autocomplete, { label: 'City', items: ['Melbourne', 'Sydney'], defaultValue: 'Mel' })),
    React.createElement('article', { 'data-component': 'checkbox-group' },
      React.createElement('h3', null, 'Checkbox group'),
      React.createElement(CheckboxGroup, { label: 'Notifications', defaultValue: ['email'] },
        React.createElement(Checkbox, { value: 'email' }, 'Email'),
        React.createElement(Checkbox, { value: 'sms' }, 'SMS'))),
    React.createElement('article', { 'data-component': 'date-field' },
      React.createElement('h3', null, 'Date field'),
      React.createElement(DateField, { label: 'Birthday', defaultValue: '2026-08-26' })),
    React.createElement('article', { 'data-component': 'date-picker' },
      React.createElement('h3', null, 'Date picker'),
      React.createElement(DatePicker, { label: 'Due date', defaultValue: '2026-08-26' })),
    React.createElement('article', { 'data-component': 'date-range-picker' },
      React.createElement('h3', null, 'Date range picker'),
      React.createElement(DateRangePicker, { label: 'Trip dates', startName: 'tripStart', endName: 'tripEnd', defaultValue: { start: '2026-08-26', end: '2026-09-01' } })),
    React.createElement('article', { 'data-component': 'form' },
      React.createElement('h3', null, 'Form'),
      React.createElement(Form, null, React.createElement(TextField, { label: 'Name', name: 'name' }), React.createElement(Button, { type: 'submit' }, 'Save'))),
    React.createElement('article', { 'data-component': 'number-field' },
      React.createElement('h3', null, 'Number field'),
      React.createElement(NumberField, { label: 'Quantity', defaultValue: 2, minValue: 0 })),
    React.createElement('article', { 'data-component': 'search-field' },
      React.createElement('h3', null, 'Search field'),
      React.createElement(SearchField, { label: 'Search', defaultValue: 'Core' })),
    React.createElement('article', { 'data-component': 'switch' },
      React.createElement('h3', null, 'Switch'),
      React.createElement(Switch, { label: 'Enabled', description: 'Allow notifications', errorMessage: 'Choose a setting', required: true, invalid: true, defaultSelected: true })),
    React.createElement('article', { 'data-component': 'text-field' },
      React.createElement('h3', null, 'Text field'),
      React.createElement(TextField, { label: 'Name', defaultValue: 'Andrew', description: 'Your display name' })),
    React.createElement('article', { 'data-component': 'time-field' },
      React.createElement('h3', null, 'Time field'),
      React.createElement(TimeField, { label: 'Start time', defaultValue: '09:30' })),
    React.createElement('article', { 'data-component': 'disclosure' },
      React.createElement('h3', null, 'Disclosure'),
      React.createElement(Disclosure, { title: 'Details', defaultExpanded: true }, 'Expanded content')),
    React.createElement('article', { 'data-component': 'disclosure-group' },
      React.createElement('h3', null, 'Disclosure group'),
      React.createElement(DisclosureGroup, { multiple: false, defaultExpandedIds: ['one'] },
        React.createElement(Disclosure, { id: 'one', title: 'One' }, 'First panel'),
        React.createElement(Disclosure, { id: 'two', title: 'Two' }, 'Second panel'))),
    React.createElement('article', { 'data-component': 'group' },
      React.createElement('h3', null, 'Group'),
      React.createElement(Group, { 'aria-label': 'Actions' }, React.createElement(Button, null, 'Save'))),
    React.createElement('article', { 'data-component': 'link' },
      React.createElement('h3', null, 'Link'),
      React.createElement(Link, { href: '/settings' }, 'Enabled'),
      React.createElement(Link, { href: '/settings', disabled: true }, 'Disabled')),
    React.createElement('article', { 'data-component': 'meter' },
      React.createElement('h3', null, 'Meter'),
      React.createElement(Meter, { label: 'Storage', value: 72 })),
    React.createElement('article', { 'data-component': 'progress-bar' },
      React.createElement('h3', null, 'Progress bar'),
      React.createElement(ProgressBar, { label: 'Upload', value: 64 }),
      React.createElement(ProgressBar, { label: 'Loading' })),
    React.createElement('article', { 'data-component': 'separator' },
      React.createElement('h3', null, 'Separator'),
      React.createElement(Separator, { orientation: 'horizontal' }),
      React.createElement(Separator, { orientation: 'vertical' })),
    React.createElement('article', { 'data-component': 'toggle-button' },
      React.createElement('h3', null, 'Toggle button'),
      React.createElement(ToggleButton, { defaultSelected: true }, 'Selected'),
      React.createElement(ToggleButton, null, 'Idle'),
      React.createElement(ToggleButton, { disabled: true }, 'Disabled')),
    React.createElement('article', { 'data-component': 'calendar' },
      React.createElement('h3', null, 'Calendar'),
      React.createElement(Calendar, { label: 'Date', defaultValue: '2026-08-26' })),
    React.createElement('article', { 'data-component': 'color-area' },
      React.createElement('h3', null, 'Color area'),
      React.createElement(ColorArea, { label: 'Color', defaultValue: '#ff0000' })),
    React.createElement('article', { 'data-component': 'color-field' },
      React.createElement('h3', null, 'Color field'),
      React.createElement(ColorField, { label: 'Color', defaultValue: '#ff0000' })),
    React.createElement('article', { 'data-component': 'color-picker' },
      React.createElement('h3', null, 'Color picker'),
      React.createElement(ColorPicker, { defaultValue: '#ff0000' }, React.createElement(ColorField, { label: 'Color' }))),
    React.createElement('article', { 'data-component': 'color-slider' },
      React.createElement('h3', null, 'Color slider'),
      React.createElement(ColorSlider, { label: 'Red', channel: 'red', defaultValue: '#ff0000' })),
    React.createElement('article', { 'data-component': 'color-swatch' },
      React.createElement('h3', null, 'Color swatch'),
      React.createElement(ColorSwatch, { color: '#ff0000' })),
    React.createElement('article', { 'data-component': 'color-swatch-picker' },
      React.createElement('h3', null, 'Color swatch picker'),
      React.createElement(ColorSwatchPicker, { 'aria-label': 'Palette', items: [{ id: 'red', color: '#ff0000' }, { id: 'blue', color: '#0000ff' }] })),
    React.createElement('article', { 'data-component': 'color-wheel' },
      React.createElement('h3', null, 'Color wheel'),
      React.createElement(ColorWheel, { 'aria-label': 'Hue', defaultValue: '#ff0000' })),
    React.createElement('article', { 'data-component': 'combo-box' },
      React.createElement('h3', null, 'Combo box'),
      React.createElement(ComboBox, { label: 'City', items: ['Melbourne', 'Sydney'] })),
    React.createElement('article', { 'data-component': 'grid-list' },
      React.createElement('h3', null, 'Grid list'),
      React.createElement(GridList, { 'aria-label': 'Grid', items: ['One', 'Two'] })),
    React.createElement('article', { 'data-component': 'list-box' },
      React.createElement('h3', null, 'List box'),
      React.createElement(ListBox, { 'aria-label': 'List', items: ['One', 'Two'] })),
    React.createElement('article', { 'data-component': 'menu' },
      React.createElement('h3', null, 'Menu'),
      React.createElement(Menu, { 'aria-label': 'Actions', items: ['Save', 'Delete'] })),
    React.createElement('article', { 'data-component': 'radio-group' },
      React.createElement('h3', null, 'Radio group'),
      React.createElement(RadioGroup, { label: 'Size', options: [{ value: 's', label: 'Small' }, { value: 'l', label: 'Large' }] })),
    React.createElement('article', { 'data-component': 'range-calendar' },
      React.createElement('h3', null, 'Range calendar'),
      React.createElement(RangeCalendar, { label: 'Trip', defaultValue: { start: '2026-08-26', end: '2026-09-01' } })),
    React.createElement('article', { 'data-component': 'select' },
      React.createElement('h3', null, 'Select'),
      React.createElement(Select, { label: 'Country', items: ['Australia', 'New Zealand'] })),
    React.createElement('article', { 'data-component': 'slider' },
      React.createElement('h3', null, 'Slider'),
      React.createElement(Slider, { label: 'Volume', defaultValue: 50 })),
    React.createElement('article', { 'data-component': 'table' },
      React.createElement('h3', null, 'Table'),
      React.createElement(Table, { 'aria-label': 'People', columns: [{ id: 'name', label: 'Name' }], rows: [{ id: 'andrew', name: 'Andrew' }] })),
    React.createElement('article', { 'data-component': 'tabs' },
      React.createElement('h3', null, 'Tabs'),
      React.createElement(Tabs, { 'aria-label': 'Sections', items: [{ id: 'one', label: 'One', panel: 'First' }, { id: 'two', label: 'Two', panel: 'Second' }] })),
    React.createElement('article', { 'data-component': 'tag-group' },
      React.createElement('h3', null, 'Tag group'),
      React.createElement(TagGroup, { label: 'Tags', items: ['Design', 'Code'] })),
    React.createElement('article', { 'data-component': 'toggle-button-group' },
      React.createElement('h3', null, 'Toggle button group'),
      React.createElement(ToggleButtonGroup, { 'aria-label': 'Formatting' }, React.createElement(ToggleButton, null, 'Bold'), React.createElement(ToggleButton, null, 'Italic'))),
    React.createElement('article', { 'data-component': 'token-field' },
      React.createElement('h3', null, 'Token field'),
      React.createElement(TokenField, { label: 'Recipients', defaultValue: ['Andrew'] })),
    React.createElement('article', { 'data-component': 'toolbar' },
      React.createElement('h3', null, 'Toolbar'),
      React.createElement(Toolbar, { 'aria-label': 'Editor' }, React.createElement(ToggleButton, null, 'Bold'))),
    React.createElement('article', { 'data-component': 'tree' },
      React.createElement('h3', null, 'Tree'),
      React.createElement(Tree, { 'aria-label': 'Files', items: [{ id: 'src', label: 'src', children: [{ id: 'main', label: 'main.jsx' }] }] })),
    React.createElement('article', { 'data-component': 'virtualizer' },
      React.createElement('h3', null, 'Virtualizer'),
      React.createElement(Virtualizer, { 'aria-label': 'Results', items: Array.from({ length: 32 }, (_, index) => `Result ${index + 1}`), height: 180 })));
}

createRoot(document.querySelector('#root')).render(React.createElement('main', null,
  React.createElement('h1', null, 'Core UI React R1.3'),
  profiles.map(([colorScheme, contrast, motion, density, direction]) => React.createElement('section', {
    key: [colorScheme, contrast, motion, density, direction].join('-'),
    'data-profile': [colorScheme, contrast, motion, density, direction].join('/'),
    'data-core-color-scheme': colorScheme,
    'data-core-contrast': contrast,
    'data-core-motion': motion,
    'data-core-density': density,
    'data-core-direction': direction,
  },
  React.createElement('h2', null, `${colorScheme} · ${contrast} · ${motion} · ${density} · ${direction}`),
  React.createElement(R1ButtonFixture),
  React.createElement(R1ButtonFixture, { disabled: true }),
  React.createElement(R1ButtonFixture, { pending: true }),
  React.createElement(ComponentStates),
  )),
));
