import React from 'react';
import { createRoot } from 'react-dom/client';
import {
  Breadcrumbs,
  Button,
  Checkbox,
  CheckboxGroup,
  Disclosure,
  DisclosureGroup,
  Autocomplete,
  DateField,
  DatePicker,
  DateRangePicker,
  Form,
  Group,
  Link,
  Meter,
  NumberField,
  ProgressBar,
  SearchField,
  Separator,
  Switch,
  TextField,
  TimeField,
  ToggleButton,
} from '@core-ui/react';
import { R1ButtonFixture } from '../../../packages/react/src/button-fixture.mjs';
import '@core-ui/react/styles.css';

const profiles = [
  ['light', 'standard', 'full', 'comfortable', 'ltr'],
  ['dark', 'standard', 'full', 'comfortable', 'ltr'],
  ['light', 'more', 'full', 'comfortable', 'ltr'],
  ['light', 'standard', 'reduced', 'comfortable', 'ltr'],
  ['light', 'standard', 'full', 'compact', 'ltr'],
  ['light', 'standard', 'full', 'comfortable', 'rtl'],
];

function ComponentStates() {
  return React.createElement(React.Fragment, null,
    React.createElement('article', { 'data-component': 'breadcrumbs' },
      React.createElement('h3', null, 'Breadcrumbs'),
      React.createElement(Breadcrumbs, { 'aria-label': 'Breadcrumb', items: [{ id: 'home', label: 'Home', href: '/' }, { id: 'docs', label: 'Docs' }] })),
    React.createElement('article', { 'data-component': 'checkbox' },
      React.createElement('h3', null, 'Checkbox'),
      React.createElement(Checkbox, { defaultChecked: true }, 'Selected'),
      React.createElement(Checkbox, { indeterminate: true }, 'Mixed'),
      React.createElement(Checkbox, { disabled: true }, 'Disabled')),
    React.createElement('article', { 'data-component': 'autocomplete' },
      React.createElement('h3', null, 'Autocomplete'),
      React.createElement(Autocomplete, { label: 'City', items: ['Melbourne', 'Sydney'], defaultValue: 'Mel' })),
    React.createElement('article', { 'data-component': 'checkbox-group' },
      React.createElement('h3', null, 'Checkbox group'),
      React.createElement(CheckboxGroup, { label: 'Notifications', defaultValue: ['email'] },
        React.createElement(Checkbox, { value: 'email' }, 'Email'),
        React.createElement(Checkbox, { value: 'sms' }, 'SMS'))),
    React.createElement('article', { 'data-component': 'date-field' },
      React.createElement('h3', null, 'Date field'),
      React.createElement(DateField, { label: 'Birthday', defaultValue: '2026-08-26' })),
    React.createElement('article', { 'data-component': 'date-picker' },
      React.createElement('h3', null, 'Date picker'),
      React.createElement(DatePicker, { label: 'Due date', defaultValue: '2026-08-26' })),
    React.createElement('article', { 'data-component': 'date-range-picker' },
      React.createElement('h3', null, 'Date range picker'),
      React.createElement(DateRangePicker, { label: 'Trip dates', startName: 'tripStart', endName: 'tripEnd', defaultValue: { start: '2026-08-26', end: '2026-09-01' } })),
    React.createElement('article', { 'data-component': 'form' },
      React.createElement('h3', null, 'Form'),
      React.createElement(Form, null, React.createElement(TextField, { label: 'Name', name: 'name' }), React.createElement(Button, { type: 'submit' }, 'Save'))),
    React.createElement('article', { 'data-component': 'number-field' },
      React.createElement('h3', null, 'Number field'),
      React.createElement(NumberField, { label: 'Quantity', defaultValue: 2, minValue: 0 })),
    React.createElement('article', { 'data-component': 'search-field' },
      React.createElement('h3', null, 'Search field'),
      React.createElement(SearchField, { label: 'Search', defaultValue: 'Core' })),
    React.createElement('article', { 'data-component': 'switch' },
      React.createElement('h3', null, 'Switch'),
      React.createElement(Switch, { label: 'Enabled', description: 'Allow notifications', errorMessage: 'Choose a setting', required: true, invalid: true, defaultSelected: true })),
    React.createElement('article', { 'data-component': 'text-field' },
      React.createElement('h3', null, 'Text field'),
      React.createElement(TextField, { label: 'Name', defaultValue: 'Andrew', description: 'Your display name' })),
    React.createElement('article', { 'data-component': 'time-field' },
      React.createElement('h3', null, 'Time field'),
      React.createElement(TimeField, { label: 'Start time', defaultValue: '09:30' })),
    React.createElement('article', { 'data-component': 'disclosure' },
      React.createElement('h3', null, 'Disclosure'),
      React.createElement(Disclosure, { title: 'Details', defaultExpanded: true }, 'Expanded content')),
    React.createElement('article', { 'data-component': 'disclosure-group' },
      React.createElement('h3', null, 'Disclosure group'),
      React.createElement(DisclosureGroup, { multiple: false, defaultExpandedIds: ['one'] },
        React.createElement(Disclosure, { id: 'one', title: 'One' }, 'First panel'),
        React.createElement(Disclosure, { id: 'two', title: 'Two' }, 'Second panel'))),
    React.createElement('article', { 'data-component': 'group' },
      React.createElement('h3', null, 'Group'),
      React.createElement(Group, { 'aria-label': 'Actions' }, React.createElement(Button, null, 'Save'))),
    React.createElement('article', { 'data-component': 'link' },
      React.createElement('h3', null, 'Link'),
      React.createElement(Link, { href: '/settings' }, 'Enabled'),
      React.createElement(Link, { href: '/settings', disabled: true }, 'Disabled')),
    React.createElement('article', { 'data-component': 'meter' },
      React.createElement('h3', null, 'Meter'),
      React.createElement(Meter, { label: 'Storage', value: 72 })),
    React.createElement('article', { 'data-component': 'progress-bar' },
      React.createElement('h3', null, 'Progress bar'),
      React.createElement(ProgressBar, { label: 'Upload', value: 64 }),
      React.createElement(ProgressBar, { label: 'Loading' })),
    React.createElement('article', { 'data-component': 'separator' },
      React.createElement('h3', null, 'Separator'),
      React.createElement(Separator, { orientation: 'horizontal' }),
      React.createElement(Separator, { orientation: 'vertical' })),
    React.createElement('article', { 'data-component': 'toggle-button' },
      React.createElement('h3', null, 'Toggle button'),
      React.createElement(ToggleButton, { defaultSelected: true }, 'Selected'),
      React.createElement(ToggleButton, null, 'Idle'),
      React.createElement(ToggleButton, { disabled: true }, 'Disabled')));
}

createRoot(document.querySelector('#root')).render(React.createElement('main', null,
  React.createElement('h1', null, 'Core UI React R1.2'),
  profiles.map(([colorScheme, contrast, motion, density, direction]) => React.createElement('section', {
    key: [colorScheme, contrast, motion, density, direction].join('-'),
    'data-profile': [colorScheme, contrast, motion, density, direction].join('/'),
    'data-core-color-scheme': colorScheme,
    'data-core-contrast': contrast,
    'data-core-motion': motion,
    'data-core-density': density,
    'data-core-direction': direction,
  },
  React.createElement('h2', null, `${colorScheme} · ${contrast} · ${motion} · ${density} · ${direction}`),
  React.createElement(R1ButtonFixture),
  React.createElement(R1ButtonFixture, { disabled: true }),
  React.createElement(R1ButtonFixture, { pending: true }),
  React.createElement(ComponentStates),
  )),
));
