import { resolve } from 'node:path';
import { registerInvalidationTests } from './delivery/invalidation.mjs';
import { registerAdvisoryTests } from './delivery/advisory.mjs';
import { registerConformanceTests } from './delivery/conformance.mjs';
import { registerDisableTests } from './delivery/disable.mjs';
import { registerGuardrailTests } from './delivery/guardrails.mjs';
import { registerHostedRoutingTests } from './delivery/hosted-routing.mjs';
import { registerOwnershipTests } from './delivery/ownership.mjs';
import { registerPacketTests } from './delivery/packet.mjs';
import { registerHandoffTests } from './delivery/handoff.mjs';
import { registerOperationalIntegrityTests } from './delivery/operational-integrity.mjs';
import { registerRollbackTests } from './delivery/rollback.mjs';
import { registerReviewRoutingTests } from './delivery/review-routing.mjs';
import { registerTemplateTests } from './delivery/templates.mjs';

const repositoryRoot = resolve(import.meta.dirname, '../../../..');

registerOwnershipTests(repositoryRoot);
registerConformanceTests(repositoryRoot);
registerInvalidationTests(repositoryRoot);
registerPacketTests(repositoryRoot);
registerReviewRoutingTests(repositoryRoot);
registerHandoffTests(repositoryRoot);
registerAdvisoryTests(repositoryRoot);
registerHostedRoutingTests(repositoryRoot);
registerRollbackTests(repositoryRoot);
registerDisableTests(repositoryRoot);
registerOperationalIntegrityTests(repositoryRoot);
registerGuardrailTests(repositoryRoot);
registerTemplateTests(repositoryRoot);
